### ISSUE TITLE
No obvious way to report issues from the app

### ISSUE THREAD

**Issue by mxmason** [jhwheeler/flow-feed#1]
Since we want these projects to emulate live products as well as possible, consider adding a link to the github repo so that people can report functionality issues from the app. This has the added benefit of telling the world who is responsible for your amazing application and showing others that you'd like to take responsibility for blunders in UX. A semantic `<footer>` is a great place for a notice like this. E.g.:

> Made by [Jackson Wheeler](https://github.com/jhwheeler), with <3. If something doesn't seem to be right with this app, please [let me know](https://github.com/jhwheeler/flow-feed/issues).

You can link to your personal portfolio or GitHub profile, if you'd like. Your "let me know" point of contact can be a few logical things:

- A link directly to the issues, as above, if you know your audience is tech-savvy
- A link to the repo's README for projects with some [established contribution guidelines](https://github.com/blog/1184-contributing-guidelines).
- A `mailto:` link if you anticipate a less-savvy audience.

**Comment by jhwheeler** [comment]
Great idea, I'll implement this today! Thanks :+1:
