### ISSUE TITLE
No accessibility notice

### ISSUE THREAD

**Issue by mxmason** [jhwheeler/flow-feed#2]
As an extension of #1: 

You may benefit from posting an accessibility notice in this and future applications. This isn't law, especially not for private contractors, but it shows a commitment to the subject and invites onlookers to report issues they experience. A notice like this could be written plainly in the footer of the app, or kept in the readme and linked to appropriately. Example:

> This project strives to comply with §508 and WCAG 2.0 guidelines as closely as possible. Please see our list of [known accessibility issues](https://github.com/jhwheeler/flow-feed/issues?q=is%3Aissue+is%3Aopen+label%3AJaccessibility).

The above hyperlink uses a query string to reference open issues on this project in a yet-hypothetical "accessibility" tag: `?q=is%3Aissue+is%3Aopen+label%3AJaccessibility`, where `%3A` is a URL-safe colon (`:`).

**Comment by jhwheeler** [comment]
Great idea, I'll add this in the readme.
